### Login Request
# @name login
POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "hash"
}

### Profile Request
# @name profile
GET http://localhost:3000/v1/auth/profile
Authorization: Bearer {{login.response.body.sessionToken}}

### Register
# @name profile
POST http://localhost:3000/v1/user/register
Content-Type: application/json

{
  "email": "test@test.com",
  "username": "test@test.com",
  "firstName": "Test",
  "lastName": "Tester",
  "password": "Test123!"
}
