### Login Request
# @name login
POST {{basepath}}/{{version}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test123!"
}

### Refresh Request
# @name refresh
GET {{basepath}}/{{version}}/auth/refresh
Authorization: Bearer {{login.response.body.sessionToken}}

### Profile Request
# @name profile
GET {{basepath}}/{{version}}/auth/profile
Authorization: Bearer {{login.response.body.sessionToken}}
